# 插件配置文件
# plugin config file
version: 1.0
# 当前配置文件版本
# config.yml version
storage: json
# json或mysql，必选项
# json or mysql
language: "zh_cn"
# 默认语言
# plugin language, en / zh_cn
debugmode: disable
# 调试模式，非必要请勿开启，开启为enabled
# enable or disable, disable as default
mysql:
# 可选项，如选择mysql则必选
# database settings
  host: localhost
  port: 3306
  database: whitelist_db
  username: root
  password: password
