# 当前配置文件版本
# config.yml version
version: 1.0

# json或mysql，必选项
# json or mysql
storage: json

# 默认语言为中文，具体可用列表请查看 readme.md 的语言支持列表！
# Plugin languages: Please refer to the language support list in readme.md!
# English: en_us
language: zh_hans

# 若存储选项选择mysql则必填下面内容
# database settings
mysql:
  host: localhost
  port: 3306
  database: whitelist_db
  username: root
  password: password
