name: JoinEULA
version: 1.0
main: com.yourname.joineula.JoinEULA
api-version: 1.20
commands:
  JoinEULA:
    description: 处理 EULA 相关的命令
    usage: /<command> <reload|remove>
permissions:
  joineula.reload:
    description: 允许重新加载 EULA
    default: op
  joineula.remove:
    description: 允许删除玩家的校验信息
    default: op
