name: WhiteList-ID
version: 1.0
main: com.yourname.wid.WhiteListID
api-version: 1.20
commands:
  wid:
    description: 白名单管理
    usage: /<command> <add|remove>
permissions:
  joineula.add:
    description: 添加白名单
    default: op
  joineula.remove:
    description: 删除白名单
    default: op
