name: WhiteList-ID
version: 1.0
main: com.yourname.wid.WhiteListID
api-version: 1.13
commands:
  wid:
    description: WhiteList-ID
    usage: /wid <add|remove> <playername> or /wid reload
permissions:
  wid.add:
    description: Add player to whitelist
    default: op
  wid.remove:
    description: Remove player from whitelist
    default: op
  wid.reload:
    description: Reload the configuration file
    default: op