name: WhiteList-ID
version: 1.6
main: com.meow.wid.WhiteListID
api-version: 1.16
commands:
  wid:
    description: WhiteList-ID
    usage: /wid <add|remove> <playername> or /wid reload or /wid convert
permissions:
  wid.add:
    description: Add player to whitelist
    default: op
  wid.remove:
    description: Remove player from whitelist
    default: op
  wid.reload:
    description: Reload the configuration file
    default: op
  wid.convert:
    description: Convert whitelist from another storage
    default: op    