name: WhiteList-ID
version: 1.0
main: com.yourname.wid.WhiteListID
api-version: 1.20
commands:
  wid:
    description: WhiteList-ID
    usage: /<command> <add|remove>
permissions:
  joineula.add:
    description: Add player to whitelist
    default: op
  joineula.remove:
    description: Remove player from whitelist
    default: op
