name: JoinEULA
version: 1.0
main: com.yourname.joineula.JoinEULA
api-version: 1.20
commands:
  JoinEULA:
    description: 重载配置文件
    usage: /<command> reload
permissions:
  joineula.reload:
    description: 允许 OP 重载配置文件
    default: op
