name: Build and Package

on:
  push:
    branches:
      - main  # 或你想要触发构建的分支
  pull_request:
    branches:
      - main  # 也可以在 PR 时触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检查库文件
        uses: actions/checkout@v2

      - name: 设置 Java 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'  # 你可以根据需要设置版本

      - name: 构建项目
        run: mvn clean package

      - name: 上传 Jar 文件
        uses: actions/upload-artifact@v2
        with:
          name: joineula-jar
          path: target/*.jar  # 打包后生成的 JAR 文件位置
