name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 更新到 v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3  # 更新到 v3
        with:
          java-version: '11'
          distribution: 'temurin'  # 指定 JDK 发行版

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: joineula-jar
          path: target/*.jar
